### ISSUE TITLE
Could not find model to load [00:03:26] DEPRECATION WARNING: please use MorganGenerator

### ISSUE THREAD

**Issue by ratanrabha** [ikmckenz/target-pred-py#36]
(target-pred-py) [root@master]#  python /home/software/target-pred-py/src/models/predict_structuretomoa.py --smiles "CC(=O)OC1=CC=CC=C1C(=O)O" --rf
Could not find model to load
[00:03:26] DEPRECATION WARNING: please use MorganGenerator
Traceback (most recent call last):
  File "/home/software/target-pred-py/src/models/predict_structuretomoa.py", line 28, in <module>
    top_output = model.predict_top_pretty(model_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/software/target-pred-py/src/models/models.py", line 75, in predict_top_pretty
    top, probabilities = self.predict_top(data, n_outputs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/software/target-pred-py/src/models/models.py", line 131, in predict_top
    model_output = self.model.predict_proba(data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/software/anaconda3/envs/target-pred-py/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 944, in predict_proba
    check_is_fitted(self)
  File "/home/software/anaconda3/envs/target-pred-py/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1661, in check_is_fitted
    raise NotFittedError(msg % {"name": type(estimator).__name__})
sklearn.exceptions.NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

**Comment by ikmckenz** [comment]
Did you train the model before trying to use it?
